package com.tintin;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2015-08-26T21:07:18.357+05:30
 * Generated source version: 3.0.0
 * 
 */
@WebService(targetNamespace = "http://tintin.com/", name = "SimpleService")
@XmlSeeAlso({ObjectFactory.class})
public interface SimpleService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "calculateBill", targetNamespace = "http://tintin.com/", className = "com.tintin.CalculateBill")
    @WebMethod
    @ResponseWrapper(localName = "calculateBillResponse", targetNamespace = "http://tintin.com/", className = "com.tintin.CalculateBillResponse")
    public com.model.BillDetails calculateBill(
        @WebParam(name = "arg0", targetNamespace = "")
        com.model.Customer arg0
    ) throws CalculationException;
}
