package com.tintin;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2015-08-25T17:00:23.330+05:30
 * Generated source version: 3.0.0
 * 
 */
@WebServiceClient(name = "SimpleServiceImplService", 
                  wsdlLocation = "file:/C:/Users/IBM_ADMIN/myworkspace/JAXWS-Service/WebContent/wsdl/simpleserviceimpl.wsdl",
                  targetNamespace = "http://tintin.com/") 
public class SimpleServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tintin.com/", "SimpleServiceImplService");
    public final static QName SimpleServiceImplPort = new QName("http://tintin.com/", "SimpleServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/IBM_ADMIN/myworkspace/JAXWS-Service/WebContent/wsdl/simpleserviceimpl.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SimpleServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/IBM_ADMIN/myworkspace/JAXWS-Service/WebContent/wsdl/simpleserviceimpl.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SimpleServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SimpleServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SimpleServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SimpleServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SimpleServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SimpleServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns SimpleService
     */
    @WebEndpoint(name = "SimpleServiceImplPort")
    public SimpleService getSimpleServiceImplPort() {
        return super.getPort(SimpleServiceImplPort, SimpleService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SimpleService
     */
    @WebEndpoint(name = "SimpleServiceImplPort")
    public SimpleService getSimpleServiceImplPort(WebServiceFeature... features) {
        return super.getPort(SimpleServiceImplPort, SimpleService.class, features);
    }

}
