package com.tintin.client;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2015-09-01T14:16:47.651+05:30
 * Generated source version: 3.0.0
 * 
 */
@WebService(targetNamespace = "http://tintin.com/", name = "SimpleService")
@XmlSeeAlso({com.tintin.ObjectFactory.class})
public interface SimpleService {

    @RequestWrapper(localName = "calculateBill", targetNamespace = "http://tintin.com/", className = "com.tintin.CalculateBill")
    @ResponseWrapper(localName = "calculateBillResponse", targetNamespace = "http://tintin.com/", className = "com.tintin.CalculateBillResponse")
    @WebMethod(operationName = "calculateBill")
    public Response<com.tintin.CalculateBillResponse> calculateBillAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        com.tintin.Customer arg0
    );

    @RequestWrapper(localName = "calculateBill", targetNamespace = "http://tintin.com/", className = "com.tintin.CalculateBill")
    @ResponseWrapper(localName = "calculateBillResponse", targetNamespace = "http://tintin.com/", className = "com.tintin.CalculateBillResponse")
    @WebMethod(operationName = "calculateBill")
    public Future<?> calculateBillAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        com.tintin.Customer arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<com.tintin.CalculateBillResponse> asyncHandler
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "calculateBill", targetNamespace = "http://tintin.com/", className = "com.tintin.CalculateBill")
    @WebMethod
    @ResponseWrapper(localName = "calculateBillResponse", targetNamespace = "http://tintin.com/", className = "com.tintin.CalculateBillResponse")
    public com.tintin.BillDetails calculateBill(
        @WebParam(name = "arg0", targetNamespace = "")
        com.tintin.Customer arg0
    ) throws CalculationException;
}
