
package com.tintin.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.0
 * Tue Aug 25 15:18:13 IST 2015
 * Generated source version: 3.0.0
 */

@XmlRootElement(name = "calculateBill", namespace = "http://tintin.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "calculateBill", namespace = "http://tintin.com/")

public class CalculateBill {

    @XmlElement(name = "arg0")
    private com.model.Customer arg0;

    public com.model.Customer getArg0() {
        return this.arg0;
    }

    public void setArg0(com.model.Customer newArg0)  {
        this.arg0 = newArg0;
    }

}

