
package com.tintin.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.0
 * Tue Aug 25 15:18:13 IST 2015
 * Generated source version: 3.0.0
 */

@XmlRootElement(name = "calculateBillResponse", namespace = "http://tintin.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "calculateBillResponse", namespace = "http://tintin.com/")

public class CalculateBillResponse {

    @XmlElement(name = "return")
    private com.model.BillDetails _return;

    public com.model.BillDetails getReturn() {
        return this._return;
    }

    public void setReturn(com.model.BillDetails new_return)  {
        this._return = new_return;
    }

}

