
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.client;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.soap.MessageFactory;
import javax.xml.soap.MimeHeader;
import javax.xml.soap.MimeHeaders;
import javax.xml.soap.SOAPConnection;
import javax.xml.soap.SOAPConnectionFactory;
import javax.xml.soap.SOAPException;
import javax.xml.soap.SOAPMessage;
import javax.xml.ws.Service;
import javax.xml.ws.soap.SOAPBinding;

import com.model.BillDetails;
import com.model.Customer;
import com.tintin.SimpleService;;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2015-08-25T15:18:13.844+05:30
 * Generated source version: 3.0.0
 * 
 */
public class SimpleServiceSAAJClient {

    public static void main(String[] args) throws Exception {
    	 /*  SIMPLE REQUEST /RESPONSE      
        <?xml version="1.0" ?><S:Envelope xmlns:S="http://www.w3.org/2003/05/soap-envelope"><S:Body><ns2:calculateBill xmlns:ns2="http://tintin.com/"><arg0><address>B-205, Silver Estate, Doltala -700132</address><age>29</age><name>Nabin Mandal</name><phone>8697042514</phone></arg0></ns2:calculateBill></S:Body></S:Envelope>
         <soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope"><soap:Body><ns2:calculateBillResponse xmlns:ns2="http://tintin.com/"><return><amount>3456</amount><billAddress>Nabin Mandal : B-205, Silver Estate, Doltala -700132</billAddress><endDate>2015-08-25T15:58:58.433+05:30</endDate><startDate>2015-08-25T15:15:46.433+05:30</startDate></return></ns2:calculateBillResponse></soap:Body></soap:Envelope>
         */
    	InputStream is =new FileInputStream(new File("C:\\Users\\IBM_ADMIN\\git\\Latest\\JAXWS\\JAXWS-Client\\src\\com\\client\\soap.txt"));
    	SOAPConnectionFactory soapCF = SOAPConnectionFactory.newInstance();
        SOAPConnection soapConnection = soapCF.createConnection();
        MimeHeaders mhs =new MimeHeaders();
        mhs.addHeader("host", "testhost");
        MessageFactory messageFactory = MessageFactory.newInstance();
        SOAPMessage requestMessage = messageFactory.createMessage(mhs,is);
        URL to = new URL("http://localhost:8080/JAXWS-Service/services/SimpleServiceImplPort?wsdl");
        SOAPMessage responseMessage = soapConnection.call(requestMessage, to);
        requestMessage.writeTo(System.out);
        System.out.println();
        responseMessage.writeTo(System.out);
       
    }

}