
package com.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.tintin.CalculationException;
import com.tintin.SimpleService;
import com.tintin.SimpleServiceImplService;


/**
 * This class was generated by Apache CXF 3.0.0
 * 2015-08-25T17:00:23.256+05:30
 * Generated source version: 3.0.0
 * 
 */
public final class SimpleServiceStaticClient {

    private static final QName SERVICE_NAME = new QName("http://model.com/", "SimpleServiceImplService");

    private SimpleServiceStaticClient() {
    }

    public static void main(String args[]) throws java.lang.Exception {
       
    	SimpleServiceImplService service = new SimpleServiceImplService();
    	SimpleService servicePort= service.getSimpleServiceImplPort();
       System.out.println("Invoking calculateBill...");
       com.model.Customer customer = new com.model.Customer();
       customer.setAddress("Address134217423");
       customer.setAge(35);
       customer.setName(" ");
       customer.setPhone("938749820");
       try{
       com.model.BillDetails bd = servicePort.calculateBill(customer);
       System.out.println("Amount : " + bd.getAmount());
       System.out.println("Address : " + bd.getBillAddress());
       }
       catch(CalculationException calex){
    	   System.out.println(calex);
       }

    }

}
